export const QUESTIONS_FETCH = 'QUESTIONS_FETCH';
export const QUESTIONS_FETCH_SUCCESS = 'QUESTIONS_FETCH_SUCCESS';
export const QUESTIONS_FETCH_FAIL = 'QUESTIONS_FETCH_FAIL';

export const QUESTION_FETCH = 'QUESTION_FETCH';
export const QUESTION_FETCH_SUCCESS = 'QUESTION_FETCH_SUCCESS';
export const QUESTION_FETCH_FAIL = 'QUESTION_FETCH_FAIL';